version: '3'
services:
  eureka-server:
    image: hbox/eureka-server:0.0.1-SNAPSHOT
    deploy:
      replicas: 2
    command: "--eureka-instance.hostname=eureka-server"
    ports:
      - "1111:8080"
  config-server:
    image: hbox/config-server:0.0.1-SNAPSHOT
    command: "--eureka.client.serviceUrl.defaultZone=http://eureka-server:8080/eureka/"
    ports:
      - "1121:8080"
  hello-service:
    image: hbox/hello-service:0.0.1-SNAPSHOT
    deploy:
      replicas: 2
    command: "--eureka.client.serviceUrl.defaultZone=http://eureka-server:8080/eureka/ --spring.cloud.config.uri=http://config-server:8080/"
    ports:
      - "1131:8080"
#  ribbon-consumer:
#    image: hbox/ribbon-consumer:0.0.1-SNAPSHOT
#    deploy:
#      replicas: 2
#    command: "--eureka.client.serviceUrl.defaultZone=http://eureka-server:8080/eureka/"
#    ports:
#      - "1141:8080"
#  feign-consumer:
#    image: hbox/feign-consumer:0.0.1-SNAPSHOT
#    command: "--eureka.client.serviceUrl.defaultZone=http://eureka-server:.8080/eureka/"
#    ports:
#      - "1151:8080"
#  turbine:
#    image: hbox/turbine:0.0.1-SNAPSHOT
#    command: "--eureka.client.serviceUrl.defaultZone=http://eureka-server:8080/eureka/"
#    ports:
#      - "1161:8080"
#      - "1162:9090"
#  hystrix-dashboard:
#    image: hbox/hystrix-dashboard:0.0.1-SNAPSHOT
#    ports:
#      - "1171:8080"
#  api-gateway:
#    image: hbox/api-gateway:0.0.1-SNAPSHOT
#    command: "--eureka.client.serviceUrl.defaultZone=http://eureka-server:8080/eureka/"
#    ports:
#      - "1181:8080"
