spring:
  application:
    name: api-gateway
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
    register-with-eureka: true
#zuul:
#  routes:
#    api-a:
#      path: /api-a/**
#      serviceId: hello-service
#    api-b:
#      path: /api-b/**
#      serviceId: feign-consumer
