spring:
  application:
    name: ribbon-consumer
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka

management:
  endpoints:
    web:
      exposure:
        include:
          - hystrix.stream
          - info
          - health
